### Create real products (save to DB)
POST http://127.0.0.1:5000/api/products
Content-Type: application/json

{
  "product_name": "مياه معدنية",
  "unit_weight": 0.5,
  "container_weight": 0.1,
  "total_weight": 12.1,
  "quantity": 10,
  "shelf_id": 1,
  "status": "Normal"
}
### Create real products (save to DB)

POST http://127.0.0.1:5000/api/products
Content-Type: application/json

{
  "rfid": "04A1B2C3D4",
  "product_type": "غذائي",
  "product_name": "سكر",
  "unit_weight": 1.0,
  "container_weight": 0.2,
  "total_weight": 10.2,
  "quantity": 10,
  "shelf_id": 1
}

### Get all products
GET http://127.0.0.1:5000/api/products

